#!/usr/bin/env bash
# Tee pipe into log file.

if test -z "$TMP"; then
    TMP=/tmp
fi

LOG="$TMP/unison-fsmonitor.log"

tee -a $LOG | RUST_LOG=debug ~/repo/unison-fsmonitor/target/debug/unison-fsmonitor 2>>$LOG | tee -a $LOG
# /usr/local/bin/unison-fsmonitor-unox 2>>$LOG | tee -a $LOG
